### ISSUE TITLE
Task #30 for BuycraftX v12.0.6 generated an exception

### ISSUE THREAD

**Issue by SrBedrock** [BuycraftPlugin/BuycraftX#148]
```` [00:04:38 WARN]: [BuycraftX] Task #30 for BuycraftX v12.0.6 generated an exception
java.lang.IllegalArgumentException: Not a valid Mojang UUID.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.4.jar:git-Paper-240]
at net.buycraft.plugin.UuidUtil.mojangUuidToJavaUuid(UuidUtil.java:21) ~[?:?]
at net.buycraft.plugin.bukkit.util.placeholder.BukkitNamePlaceholder.replace(BukkitNamePlaceholder.java:21) ~[?:?]
at net.buycraft.plugin.execution.placeholder.PlaceholderManager.doReplace(PlaceholderManager.java:19) ~[?:?]
at net.buycraft.plugin.execution.strategy.QueuedCommandExecutor.run(QueuedCommandExecutor.java:70) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-240]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-240]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]```

**Comment by SrBedrock** [comment]
```
[18:30:52 WARN]: [BuycraftX] Task #39 for BuycraftX v12.0.6 generated an exception
java.lang.IllegalArgumentException: Not a valid Mojang UUID.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.4.jar:git-Paper-240]
at net.buycraft.plugin.UuidUtil.mojangUuidToJavaUuid(UuidUtil.java:21) ~[?:?]
at net.buycraft.plugin.bukkit.util.placeholder.BukkitNamePlaceholder.replace(BukkitNamePlaceholder.java:21) ~[?:?]
at net.buycraft.plugin.execution.placeholder.PlaceholderManager.doReplace(PlaceholderManager.java:19) ~[?:?]
at net.buycraft.plugin.execution.strategy.QueuedCommandExecutor.run(QueuedCommandExecutor.java:70) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-240]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-240]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-240]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
```

**Comment by SrBedrock** [comment]
```>.... [18:56:21 WARN]: [BuycraftX] Task #55 for BuycraftX v12.0.6 generated an exception
java.lang.IllegalArgumentException: Not a valid Mojang UUID.
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.14.4.jar:git-Paper-243]
at net.buycraft.plugin.UuidUtil.mojangUuidToJavaUuid(UuidUtil.java:21) ~[?:?]
at net.buycraft.plugin.bukkit.util.placeholder.BukkitNamePlaceholder.replace(BukkitNamePlaceholder.java:21) ~[?:?]
at net.buycraft.plugin.execution.placeholder.PlaceholderManager.doReplace(PlaceholderManager.java:19) ~[?:?]
at net.buycraft.plugin.execution.strategy.QueuedCommandExecutor.run(QueuedCommandExecutor.java:70) ~[?:?]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.4.jar:git-Paper-243]
at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1171) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:417) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1098) ~[patched_1.14.4.jar:git-Paper-243]
at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:925) ~[patched_1.14.4.jar:git-Paper-243]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

**Comment by lachepootje** [comment]
Im having this problem too

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
