### ISSUE TITLE
[BuycraftX] Could not fetch due players queue

### ISSUE THREAD

**Issue by SrBedrock** [BuycraftPlugin/BuycraftX#152]
```
>.... [16:11:36 ERROR]: [BuycraftX] Could not fetch due players queue
java.net.SocketTimeoutException: timeout
at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:59) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[?:?]
at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[?:?]
at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:62) ~[?:?]
at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:38) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"84d7587"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Tuinity-"84d7587"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Tuinity-"84d7587"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by andrewkm** [comment]
This is BuyCraftX being stupid and not only setting the verbose to true by default for all new users/customers, but also settings something to an ERROR level log that literally should never be an ERROR.

**Comment by SrBedrock** [comment]
Understand! Verbose set to false.

**Comment by JustFerrix** [comment]
Hi! I've got also the same problem, can someone help me with this? Thank you!

[17:07:47 ERROR]: [BuycraftX] Could not fetch due players queue
java.net.SocketTimeoutException: timeout
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:59) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:62) ~[BuycraftX.jar:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:38) ~[BuycraftX.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.jar:git-Paper-69]
        at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.jar:git-Paper-69]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
