### ISSUE TITLE
[BuycraftX] Failed to send analytic events!

### ISSUE THREAD

**Issue by SrBedrock** [BuycraftPlugin/BuycraftX#153]
```
[13:35:46 ERROR]: [BuycraftX] Failed to send analytic events!
net.buycraft.plugin.BuyCraftAPIException: Unexpected content-type text/html; charset=UTF-8
at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:67) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[?:?]
at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[?:?]
at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[?:?]
at net.buycraft.plugin.execution.ServerEventSenderTask.run(ServerEventSenderTask.java:39) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Tuinity-"99854e9"]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by andrewkm** [comment]
This is BuyCraftX being stupid and not only setting the verbose to true by default for all new users/customers, but also settings something to an ERROR level log that literally should never be an ERROR.

**Comment by SrBedrock** [comment]
Understand! Verbose set to false.
