### ISSUE TITLE
exception while executing task 99

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#159]
Entire console being spammed with this across all servers on the network, restarts do not help.
Has this plugin and it's Github issues been abandoned? @LeeMcNeil @liam-wiltshire 

```
[06:14:10] [Craft Scheduler Thread - 3/WARN]: [BuycraftX] Plugin BuycraftX v12.0.6 generated an exception while executing task 99
java.lang.IllegalArgumentException: Not a valid Mojang UUID.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[patched_1.12.2.jar:git-Paper-1618]
	at net.buycraft.plugin.UuidUtil.mojangUuidToJavaUuid(UuidUtil.java:21) ~[?:?]
	at net.buycraft.plugin.bukkit.BukkitBuycraftPlatformBase.getPlayer(BukkitBuycraftPlatformBase.java:67) ~[?:?]
	at net.buycraft.plugin.bukkit.BukkitBuycraftPlatformBase.isPlayerOnline(BukkitBuycraftPlatformBase.java:74) ~[?:?]
	at net.buycraft.plugin.execution.DuePlayerFetcher.processOnlinePlayers(DuePlayerFetcher.java:112) ~[?:?]
	at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:98) ~[?:?]
	at net.buycraft.plugin.bukkit.command.ForceCheckSubcommand.lambda$execute$0(ForceCheckSubcommand.java:31) ~[?:?]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64) ~[patched_1.12.2.jar:git-Paper-1618]
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) ~[patched_1.12.2.jar:git-Paper-1618]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.12.2.jar:git-Paper-1618]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) [?:?]
	at java.lang.Thread.run(Thread.java:832) [?:?]
```

**Comment by liam-wiltshire** [comment]
Hi @andrewkm 

Just to confirm, this isn't a bug with the plugin - the bug is with the data being returned by the API - as the plugin is getting invalid data, it is then correctly throwing an exception. I appreciate from a user-side it's difficult to know when something is a problem with the plugin or when it's not.

We are working to rectify the root cause - in the meantime I have fixed the impacted commands.

**Comment by andrewkm** [comment]
Yes, it's clear the problem lies on the info the plugin is getting, however is there any way for a user to resolve these errors themselves via the Tebex panel?
