### ISSUE TITLE
Legacy Material Support getting initialized in modern versions

### ISSUE THREAD

**Issue by Artuto** [BuycraftPlugin/BuycraftX#174]
Legacy Material Supports gets initialized in modern versions (1.16.5):

```
[21:08:36 INFO]: [BuycraftX] Enabling BuycraftX v12.0.6
[21:08:36 INFO]: [BuycraftX] Validating your server key...
[21:08:37 INFO]: [BuycraftX] Fetching all server packages...
[21:08:37 WARN]: Initializing Legacy Material Support. Unless you have legacy plugins and/or data this is a bug!
[21:08:37 WARN]: java.lang.Exception
[21:08:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.legacy.CraftLegacy.<clinit>(CraftLegacy.java:259)
[21:08:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.util.CraftMagicNumbers.fromLegacy(CraftMagicNumbers.java:197)
[21:08:37 WARN]:        at org.bukkit.Material.getMaterial(Material.java:4615)
[21:08:37 WARN]:        at org.bukkit.Material.matchMaterial(Material.java:4660)
[21:08:37 WARN]:        at net.buycraft.plugin.bukkit.BukkitBuycraftPlatform.createItemFromMaterialString(BukkitBuycraftPlatform.java:54)
[21:08:37 WARN]:        at net.buycraft.plugin.bukkit.gui.ViewCategoriesGUI.createInventoryFromListing(ViewCategoriesGUI.java:108)
[21:08:37 WARN]:        at net.buycraft.plugin.bukkit.gui.ViewCategoriesGUI.update(ViewCategoriesGUI.java:96)
[21:08:37 WARN]:        at net.buycraft.plugin.bukkit.BuycraftPluginBase.onEnable(BuycraftPluginBase.java:180)
[21:08:37 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[21:08:37 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
[21:08:37 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
[21:08:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:500)
[21:08:37 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:414)
[21:08:37 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:466)
[21:08:37 WARN]:        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:243)
[21:08:37 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:938)
[21:08:37 WARN]:        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175)
[21:08:37 WARN]:        at java.base/java.lang.Thread.run(Thread.java:834)
```

It traces back to the code that generates the GUI, however, legacy materials are not available since this plugin declares an api version of 1.13.

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
