### ISSUE TITLE
Emoji in package name breaks /buy on Sponge

### ISSUE THREAD

**Issue by johnfriedrich** [BuycraftPlugin/BuycraftX#176]
Hi, using 12.0.6 on Sponge 7.3.0.

When having an emoji in one of the packages in a category, you get the following error and the category items do not display.
Package name:
"Oster-Care Paket 🐰"

Errror:

```[01:34:40] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'sponge:callback 1ed2125c-3c03-461f-8687-83f1b64f01c8' for source EntityPlayerMP['I9hdkill'/541287, l='world', x=1589.94, y=76.50, z=-2250.91]: 128048
java.lang.ArrayIndexOutOfBoundsException: 128048
	at org.spongepowered.common.service.pagination.PaginationCalculator.getWidth(PaginationCalculator.java:126) ~[PaginationCalculator.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.service.pagination.PaginationCalculator.getWidth(PaginationCalculator.java:191) ~[PaginationCalculator.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.service.pagination.PaginationCalculator.getLines(PaginationCalculator.java:107) ~[PaginationCalculator.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.service.pagination.SpongePaginationList.lambda$sendTo$0(SpongePaginationList.java:114) ~[SpongePaginationList.class:1.12.2-2838-7.3.0]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_241]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_241]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_241]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_241]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499) ~[?:1.8.0_241]
	at org.spongepowered.common.service.pagination.SpongePaginationList.sendTo(SpongePaginationList.java:116) ~[SpongePaginationList.class:1.12.2-2838-7.3.0]
	at org.spongepowered.api.service.pagination.PaginationList.sendTo(PaginationList.java:114) ~[PaginationList.class:1.12.2-2838-7.3.0]
	at org.spongepowered.api.service.pagination.PaginationList$Builder.sendTo(PaginationList.java:254) ~[PaginationList$Builder.class:1.12.2-2838-7.3.0]
	at net.buycraft.plugin.sponge.command.ListPackagesCmd.sendPaginatedMessage(ListPackagesCmd.java:68) ~[ListPackagesCmd.class:?]
	at net.buycraft.plugin.sponge.command.ListPackagesCmd.lambda$sendPaginatedMessage$0(ListPackagesCmd.java:55) ~[ListPackagesCmd.class:?]
	at org.spongepowered.common.text.action.SpongeCallbackHolder.lambda$createCommand$0(SpongeCallbackHolder.java:96) ~[SpongeCallbackHolder.class:1.12.2-2838-7.3.0]
	at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) ~[CommandSpec.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) ~[SpongeCommandDispatcher.class:1.12.2-2838-7.3.0]
	at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.0]
	at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
	at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
	at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
	at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.3.0]
	at net.minecraft.network.PacketThreadUtil$1.redirect$zlf000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_241]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_241]
	at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
	at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
	at net.minecraft.server.MinecraftServer.redirect$zjj000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]```

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
