### ISSUE TITLE
Console Error Spam

### ISSUE THREAD

**Issue by kolakz** [BuycraftPlugin/BuycraftX#178]
I keep getting the following spammed in console:

[08:16:31 WARN]: [BuycraftX] Plugin BuycraftX v12.0.6 generated an exception while executing task 24
net.buycraft.plugin.BuyCraftAPIException: null
        at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:71) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[?:?]
        at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[?:?]
        at net.buycraft.plugin.shared.tasks.ListingUpdateTask.run(ListingUpdateTask.java:32) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"1222573"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"1222573"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"1222573"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[08:22:08 WARN]: [BuycraftX] Plugin BuycraftX v12.0.6 generated an exception while executing task 101189
net.buycraft.plugin.BuyCraftAPIException: null
        at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:71) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[?:?]
        at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[?:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:62) ~[?:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Tuinity-"1222573"]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Tuinity-"1222573"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Tuinity-"1222573"]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[?:?]
        at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
