### ISSUE TITLE
Not fetching players

### ISSUE THREAD

**Issue by ZaidSu** [BuycraftPlugin/BuycraftX#185]
This is my first time getting this error it just happened randomly I don't know what actually caused this, but I just don't want to get this error again or maybe I did something wrong?
```
[21:08:44 ERROR]: [BuycraftX] Could not fetch due players queue
java.net.SocketTimeoutException: timeout
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:59) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[?:?]
        at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[?:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:62) ~[?:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:38) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100) ~[patched_1.16.5.jar:git-Purpur-1171]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1171]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1171]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
        ```

**Comment by ZaidSu** [comment]
I also now keep getting the error randomly still

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
