### ISSUE TITLE
NoSuchMethodException

### ISSUE THREAD

**Issue by Jaoow** [BuycraftPlugin/BuycraftX#186]
Trying to create a Giftcard using the BuycraftAPI, I ran into this error:
```
[12:53:28 ERROR]: Caused by: java.lang.reflect.UndeclaredThrowableException
[12:53:28 ERROR]:       at jdk.proxy5/jdk.proxy5.$Proxy21.createGiftCard(Unknown Source)
[12:53:28 ERROR]:       ... 47 more
[12:53:28 ERROR]: Caused by: java.lang.NoSuchMethodException: java.lang.invoke.MethodHandles$Lookup.<init>(java.lang.Class,int)
[12:53:28 ERROR]:       at java.base/java.lang.Class.getConstructor0(Class.java:3517)
[12:53:28 ERROR]:       at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2691)
[12:53:28 ERROR]:       at retrofit2.Platform$Java8.invokeDefaultMethod(Platform.java:102)
[12:53:28 ERROR]:       at retrofit2.Retrofit$1.invoke(Retrofit.java:145)
[12:53:28 ERROR]:       ... 48 more
```

Apparently, this method has been removed since Java 14

Environment:
Java 16
Bungeecord
Windows 10

**Comment by entity** [comment]
Hi there,

Thanks for taking the time to report this issue, I'm sorry it's been slow to get resolved — we're working on it!

Unfortunately, this issue is old enough that we've had to close it. But if you see any other issues (especially ones with the same or similar symptoms), please reply here and I'll look into getting them fixed.

We are currently planning a recode of the Buycraft plugin at some point in Q2 of this year, and we would love to know what issues still exist so they can be fixed for the new plugin.

Apologies for the issues you have faced!
