### ISSUE TITLE
Fix player queue and analytics errors.

### ISSUE THREAD

**Issue by andrewkm** [BuycraftPlugin/BuycraftX#201]
```
[01:35:40] [Craft Scheduler Thread - 13628 - BuycraftX/ERROR]: [BuycraftX] Failed to send analytic events!
net.buycraft.plugin.BuyCraftAPIException: Unexpected content-type text/html; charset=UTF-8
	at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:67) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.execution.ServerEventSenderTask.run(ServerEventSenderTask.java:39) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-384]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-384]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
[01:35:40] [Craft Scheduler Thread - 13638 - BuycraftX/WARN]: [BuycraftX] Plugin BuycraftX v12.0.8 generated an exception while executing task 27
net.buycraft.plugin.BuyCraftAPIException: Unexpected content-type text/html; charset=UTF-8
	at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:67) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.internal.retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at net.buycraft.plugin.shared.tasks.ListingUpdateTask.run(ListingUpdateTask.java:32) ~[buycraftx-bukkit-post-1.13-12.0.8.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.19.3.jar:git-Paper-384]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.19.3.jar:git-Paper-384]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.19.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
```

Just because the service isn't functioning doesn't mean we need [ERROR] level logs.
Please change to [WARN] or [INFO].

**Comment by entity** [comment]
Hey Andrew,

Thanks for sending this across - what would be a solution that you would prefer to be shown here instead?

**Comment by detobel36** [comment]
In my opinion, an error is okay, but may be not all the stack trace... 😝 

And a better message that just say that it is linked to problem of the target server and not a problem of config.

**Comment by andrewkm** [comment]
> Hey Andrew,
> 
> 
> 
> Thanks for sending this across - what would be a solution that you would prefer to be shown here instead?

Anything that isn't an ERROR level.
[WARN] or [INFO] level would be optimal.
With the amount of times this happens, it shouldn't be shooting ERRORs.

**Comment by andrewkm** [comment]
Within a three day time frame, you have shot an [ERROR] due to not being able to fetch players, or not being able to send analytics a total of 12 times. No other plugin or service acts like this.

https://i.imgur.com/oAOl0eN.png

These issues are very well known and have been happening for years, it's quite silly tbh.
About time this one stops being ignored and gets fixed. It's literally a one liner fix.
https://github.com/tebexio/BuycraftX/issues/200 https://github.com/tebexio/BuycraftX/issues/185  https://github.com/tebexio/BuycraftX/issues/181 https://github.com/tebexio/BuycraftX/issues/161 https://github.com/tebexio/BuycraftX/issues/153 https://github.com/tebexio/BuycraftX/issues/152 https://github.com/tebexio/BuycraftX/issues/40 https://github.com/tebexio/BuycraftX/issues/43 https://github.com/tebexio/BuycraftX/issues/38 https://github.com/tebexio/BuycraftX/issues/41

**Comment by entity** [comment]
> Within a three day time frame, you have shot an [ERROR] due to not being able to fetch players, or not being able to send analytics a total of 12 times. No other plugin or service acts like this.
> 
> https://i.imgur.com/oAOl0eN.png
> 
> These issues are very well known and have been happening for years, it's quite silly tbh. About time this one stops being ignored and gets fixed. It's literally a one liner fix. #200 #185 #181 #161 #153 #152 #40 #43 #38 #41

Hey buddy,

Sorry to hear with the issues you’re facing, I promise it hasn’t been intended to be ignored. Lots of preparation work is going into a brand new rebuilt plugin.

I am part of the integration team, and I’ll be taking lead in our new plugin. I will certainly note this feedback.

**Comment by wsman217** [comment]
I hate to help you out Andrew because of previous encounters with you but, I have recompiled the plugin to exclude the outputting of the error exception. Here is the jar. I will be making a pr so others can build it from src if they would like. https://drive.google.com/file/d/1pjaW_JP9ZY_aFfeMixcjlvvlVR_sTs0T/view?usp=sharing

**Comment by entity** [comment]
> I hate to help you out Andrew because of previous encounters with you but, I have recompiled the plugin to exclude the outputting of the error exception. Here is the jar. I will be making a pr so others can build it from src if they would like. https://drive.google.com/file/d/1pjaW_JP9ZY_aFfeMixcjlvvlVR_sTs0T/view?usp=sharing

Thanks for being willing to send over a P.R.

**Comment by andrewkm** [comment]
> I hate to help you out Andrew because of previous encounters with you but, I have recompiled the plugin to exclude the outputting of the error exception. Here is the jar. I will be making a pr so others can build it from src if they would like. https://drive.google.com/file/d/1pjaW_JP9ZY_aFfeMixcjlvvlVR_sTs0T/view?usp=sharing

I have no idea who you are, sorry.
There's no need for comments like that in the Github issue section as well.

**Comment by wsman217** [comment]
PR is in https://github.com/tebexio/BuycraftX/pull/202 also added a note in the contributing to help some people who may not fully understand maven on how to build the project.

**Comment by entity** [comment]
Hi again,

I'm just following up to let you know that we have now added this bug to our internal tracking system.

Our team is currently working on a number of important projects, including a recode of the Buycraft plugin this quarter. We will keep your bug in mind as we work on this update and will note it in our development roadmap.

Since we have now noted your bug in our internal tracking system, we will be closing this GitHub ticket. However, if you have any further suggestions or feedback, please don't hesitate to open a new ticket and we'll be happy to take a look.

Thanks again for reporting this bug and for your continued support of Tebex.

Best regards,
The Integrations Team.
