### ISSUE TITLE
 [BuycraftX]: Could not fetch due players queue java.net.SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by NixsSa2d** [BuycraftPlugin/BuycraftX#208]
[14:32:32 ERROR] [BuycraftX]: Could not fetch due players queue
java.net.SocketTimeoutException: timeout
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.BuyCraftAPI$1.intercept(BuyCraftAPI.java:59) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.BuyCraftAPI$2.intercept(BuyCraftAPI.java:53) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254) ~[?:?]
        at net.buycraft.plugin.internal.okhttp3.RealCall.execute(RealCall.java:92) ~[?:?]
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:186) ~[?:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:62) ~[?:?]
        at net.buycraft.plugin.execution.DuePlayerFetcher.run(DuePlayerFetcher.java:38) ~[?:?]
        at net.md_5.bungee.scheduler.BungeeTask.run(Unknown Source) ~[XCord.jar:git:Travertine-Bootstrap:1.19-R0.1-SNAPSHOT:61ed3af:unknown]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by AceSardonyx** [comment]
#205

**Comment by WildBamaBoy** [comment]
Hey there, we've identified this as a problem with our API infrastructure and have made the needed fixes. This should no longer be a recurring problem.
