### ISSUE TITLE
/buy command generates lines in the chat..

### ISSUE THREAD

**Issue by hfmachin** [BuycraftPlugin/BuycraftX#26]
[11:36:45] [Server thread/INFO]: BitterBrush issued server command: /buy
[11:36:48] [pool-3-thread-26/WARN]: Exception in thread "pool-3-thread-26" 
[11:36:48] [pool-3-thread-26/WARN]: org.apache.commons.lang.UnhandledException: Plugin BuycraftX v0.1.2-SNAPSHOT generated an exception while executing task 635
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.entity.Player.spigot()Lorg/bukkit/entity/Player$Spigot;
    at net.buycraft.plugin.bukkit.tasks.SendCheckoutLink.run(SendCheckoutLink.java:35)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:53)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

**Comment by minecrafter** [comment]
This user is using _CraftBukkit_ 1.9 from Spigot, not actual Spigot 1.9.

Looks like I'll have to give in and switch BuycraftX over to Fanciful...

**Comment by minecrafter** [comment]
Resolved by moving to Fanciful
