### ISSUE TITLE
No class defined error

### ISSUE THREAD

**Issue by hfmachin** [BuycraftPlugin/BuycraftX#3]
[13:31:53] [Server thread/ERROR]: Error occurred while enabling BuycraftX v0.1-SNAPSHOT (Is it up to date?) 
java.lang.NoClassDefFoundError: com/google/gson/Gson 
at net.buycraft.plugin.bukkit.signs.purchases.RecentPurchaseSignStorage.<init>(RecentPurchaseSignStorage.java:20) ~[?:?] 
at net.buycraft.plugin.bukkit.BuycraftPlugin.onEnable(BuycraftPlugin.java:148) ~[?:?] 
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot.jar:git-Spigot-9a88a38-2ba7357] 
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:352) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:313) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:494) [spigot.jar:git-Spigot-9a88a38-2ba7357] 
at java.lang.Thread.run(Unknown Source) [?:1.7.0_80] 
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson 
at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80] 
at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_80] 
at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_80] 
at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_80] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-9a88a38-2ba7357] 
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-9a88a38-2ba7357] 
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80] 
at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_80] 
... 13 more

**Comment by minecrafter** [comment]
This user is running an extremely old version of Spigot 1.8 and needs to update.
