### ISSUE TITLE
1.7.10 Thermos Error On Package Link

### ISSUE THREAD

**Issue by Time6628** [BuycraftPlugin/BuycraftX#42]
When you click on an item in the buycraftx gui with 1.7.10 thermos: http://prntscr.com/anfsu4
Error:

```
21:44:09 [Server] WARN Exception in thread "Craft Scheduler Thread - 128" 
21:44:09 [Server] WARN org.apache.commons.lang.UnhandledException: Plugin BuycraftX v10.0 generated an exception while executing task 34270
21:44:09 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
21:44:09 [Server] INFO at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
21:44:09 [Server] INFO at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
21:44:09 [Server] INFO at java.lang.Thread.run(Thread.java:745)
21:44:09 [Server] INFO Caused by: java.lang.NullPointerException
21:44:09 [Server] INFO at net.buycraft.plugin.internal.fanciful.FancyMessage.<init>(FancyMessage.java:89)
21:44:09 [Server] INFO at net.buycraft.plugin.internal.fanciful.FancyMessage.<init>(FancyMessage.java:78)
21:44:09 [Server] INFO at net.buycraft.plugin.bukkit.tasks.SendCheckoutLink.run(SendCheckoutLink.java:34)
21:44:09 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftTask.run(CraftTask.java:71)
21:44:09 [Server] INFO at org.bukkit.craftbukkit.v1_7_R4.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
21:44:09 [Server] INFO ... 3 more
```

**Comment by minecrafter** [comment]
BuycraftX is not compatible with Minecraft 1.7.10, nor with (K)Cauldron.

**Comment by Time6628** [comment]
Are we allowed to modify it to work with 1.7.10?

**Comment by minecrafter** [comment]
Yes, the plugin is open-source under the MIT license.

**Comment by Time6628** [comment]
Cool beans :smile_cat:

**Comment by Time6628** [comment]
Already fixed it :smile_cat: https://github.com/KookykraftMC/BuycraftX/tree/MC1710
