### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by hfmachin** [BuycraftPlugin/BuycraftX#54]
[00:08:50] [Craft Scheduler Thread - 1483/WARN]: Exception in thread "Craft Scheduler Thread - 1483" 
[00:08:50] [Craft Scheduler Thread - 1483/WARN]: org.apache.commons.lang.UnhandledException: Plugin BuycraftX v10.0 generated an exception while executing task 590211
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
    at com.google.gson.Gson.fromJson(Gson.java:803)
    at com.google.gson.Gson.fromJson(Gson.java:741)
    at net.buycraft.plugin.client.ProductionApiClient.deleteCommand(ProductionApiClient.java:103)
    at net.buycraft.plugin.execution.strategy.QueuedCommandExecutor$1.run(QueuedCommandExecutor.java:81)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftTask.run(CraftTask.java:58)
    at org.bukkit.craftbukkit.v1_9_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 4 more
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
    at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
    at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
    ... 10 more

**Comment by minecrafter** [comment]
Probably CloudFlare-related

**Comment by minecrafter** [comment]
BuycraftX now handles this better.
