### ISSUE TITLE
java.lang.IndexOutOfBoundsException on recent purchases signs

### ISSUE THREAD

**Issue by ghost** [BuycraftPlugin/BuycraftX#59]
```
[03:05:25 WARN]: Exception in thread "Craft Scheduler Thread - 11"
[03:05:25 WARN]: org.apache.commons.lang.UnhandledException: Plugin BuycraftX v10.1.1 generated an exception while executing task 94
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IndexOutOfBoundsException: Index: 6, Size: 6
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at net.buycraft.plugin.bukkit.tasks.SignUpdater.run(SignUpdater.java:54)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
```

It happens when you add recent purchases signs and there is none (It should work anyway, because there will be in the future)

**Comment by minecrafter** [comment]
Update your BuycraftX: http://ci.buycraft.net/job/BuycraftX/

**Comment by ghost** [comment]
![screenshot_45](https://cloud.githubusercontent.com/assets/11008016/17086517/7d4b9aa2-51ca-11e6-9e49-788604485c37.png)

Happens on latest version

**Comment by TiTo-418** [comment]
@minecrafter
