### ISSUE TITLE
Nukkit not work

### ISSUE THREAD

**Issue by ghost** [BuycraftPlugin/BuycraftX#92]
21:15:07 [INFO] [BuycraftX] Updating coupon list...
21:15:13 [ERROR] [BuycraftX] Error whilst retrieving coupon listing
net.buycraft.plugin.client.ApiException: Unable to connect to API
        at net.buycraft.plugin.client.ProductionApiClient.get(ProductionApiClient.java:82)
        at net.buycraft.plugin.client.ProductionApiClient.get(ProductionApiClient.java:59)
        at net.buycraft.plugin.client.ProductionApiClient.getAllCoupons(ProductionApiClient.java:162)
        at net.buycraft.plugin.shared.tasks.CouponUpdateTask.run(CouponUpdateTask.java:39)
        at cn.nukkit.scheduler.TaskHandler.run(TaskHandler.java:99)
        at cn.nukkit.scheduler.ServerScheduler.mainThreadHeartbeat(ServerScheduler.java:283)
        at cn.nukkit.Server.tick(Server.java:1026)
        at cn.nukkit.Server.tickProcessor(Server.java:820)
        at cn.nukkit.Server.start(Server.java:799)
        at cn.nukkit.Server.<init>(Server.java:470)
        at cn.nukkit.Nukkit.main(Nukkit.java:102)

Nukkit used: https://github.com/BedrockCommunity/Nukkit

**Comment by liam-wiltshire** [comment]
This doesnt' look like a plugin specifically, rather the server was unable to connect to the API. This could have been a transitory issue or an issue with your server being blocked for example. If you have further problems in this regard in future, please contact support.
